apiVersion: kyverno.io/v1
kind: ClusterPolicy
metadata:
  name: add-monitoring-node-taint
  annotations:
    policies.kyverno.io/title: Taint Monitoring Node
    policies.kyverno.io/description: >-
      Automatically adds taint and label to k8s-monitoring-1 node
      to ensure only monitoring workloads run on it.
spec:
  background: true
  mutateExistingOnPolicyUpdate: true
  rules:
  - name: taint-and-label-monitoring-node
    match:
      any:
      - resources:
          kinds:
          - Node
          names:
          - k8s-monitoring-1
    mutate:
      patchStrategicMerge:
        metadata:
          labels:
            monitoring: "true"
            node-role.kubernetes.io/monitoring: ""
        spec:
          taints:
          - key: monitoring
            value: "true"
            effect: NoSchedule