redis:
  architecture: standalone
  
  auth:
    enabled: true
    password: "changeme123"
  
  master:
    # Disable persistence - NOTE THE INDENTATION
    persistence:
      enabled: false
    
    resources:
      limits:
        memory: 2Gi
        cpu: 1000m
      requests:
        memory: 1Gi
        cpu: 500m
    
    # Node affinity
    nodeSelector:
      redis: "true"
    
    # CRITICAL: Tolerate the monitoring taint
    tolerations:
      - key: "monitoring"
        operator: "Equal"
        value: "true"
        effect: "NoSchedule"
    
    # Redis memory config
    configuration: |-
      maxmemory 1600mb
      maxmemory-policy allkeys-lru
  
  metrics:
    enabled: false