redis:
  architecture: standalone
  
  auth:
    enabled: true
    password: "changeme123"
  
  master:
    # Disable persistence - pure in-memory for learning
    persistence:
      enabled: false
    
    resources:
      limits:
        memory: 2Gi      # Bump this up since you have resources
        cpu: 1000m
      requests:
        memory: 1Gi
        cpu: 500m
    
    # Node affinity to land on k8s-monitoring-1
    nodeSelector:
      redis: "true"
    
    # Optional: Use affinity for more control
    # affinity:
    #   nodeAffinity:
    #     requiredDuringSchedulingIgnoredDuringExecution:
    #       nodeSelectorTerms:
    #       - matchExpressions:
    #         - key: redis
    #           operator: In
    #           values:
    #           - "true"
  
  # Set Redis's internal memory limit (80% of K8s limit)
  master:
    configuration: |-
      maxmemory 1600mb
      maxmemory-policy allkeys-lru
  
  metrics:
    enabled: false