apiVersion: v2
name: promtail
description: Promtail log shipper for Kubernetes
type: application
version: 1.0.0
dependencies:
- name: promtail
  version: "6.17.0"
  repository: https://grafana.github.io/helm-charts