apiVersion: v2
name: monitoring
description: Prometheus and Grafana monitoring stack
type: application
version: 1.0.0
dependencies:
- name: kube-prometheus-stack
  version: "56.6.2"
  repository: https://prometheus-community.github.io/helm-charts