apiVersion: v2
name: monitoring
description: Prometheus and Grafana monitoring stack (no persistence)
type: application
version: 1.0.0
dependencies:
- name: kube-prometheus-stack
  version: "77.14.0"
  repository: https://prometheus-community.github.io/helm-charts