{{- if .Values.cloudflared.tunnelToken }}
apiVersion: v1
kind: Secret
metadata:
  name: cloudflared-secret
  namespace: {{ .Release.Namespace }}
  labels:
    app: cloudflared
type: Opaque
data:
  token: {{ .Values.cloudflared.tunnelToken | b64enc | quote }}
{{- end }}