---
apiVersion: metallb.io/v1beta1
kind: IPAddressPool
metadata:
  name: {{ .Values.ipAddressPool.name }}
  namespace: {{ .Release.Namespace }}
spec:
  addresses:
  {{- range .Values.ipAddressPool.addresses }}
  - {{ . }}
  {{- end }}
---
apiVersion: metallb.io/v1beta1
kind: L2Advertisement
metadata:
  name: {{ .Values.l2Advertisement.name }}
  namespace: {{ .Release.Namespace }}
spec:
  ipAddressPools:
  - {{ .Values.ipAddressPool.name }}