apiVersion: v2
name: loki
description: Loki log aggregation with persistent storage
type: application
version: 1.0.0
dependencies:
- name: loki
  version: "6.42.0"
  repository: https://grafana.github.io/helm-charts