loki:
  auth_enabled: false
  
  commonConfig:
    replication_factor: 1
  
  storage:
    type: filesystem
    bucketNames:
      chunks: chunks
      ruler: ruler
      admin: admin
    filesystem:
      chunks_directory: /var/loki/chunks
      rules_directory: /var/loki/rules
  
  # REQUIRED: Schema configuration
  schemaConfig:
    configs:
    - from: 2024-04-01
      store: tsdb
      object_store: filesystem
      schema: v13
      index:
        prefix: loki_index_
        period: 24h
  
  # Limits and retention
  limits_config:
    retention_period: 30d
    ingestion_rate_mb: 10
    ingestion_burst_size_mb: 20
  
  # Compactor for retention
  compactor:
    working_directory: /var/loki/compactor
    compaction_interval: 10m
    retention_enabled: true
    retention_delete_delay: 2h
    retention_delete_worker_count: 150
  
  # Single binary mode
  deploymentMode: SingleBinary
  
  singleBinary:
    replicas: 1
    
    # Persistent storage
    persistence:
      enabled: true
      size: 80Gi
      storageClassName: "local-path"
    
    resources:
      requests:
        memory: 512Mi
        cpu: 250m
      limits:
        memory: 2Gi
        cpu: 1000m
    
    # Run ONLY on monitoring node
    tolerations:
    - key: "monitoring"
      operator: "Equal"
      value: "true"
      effect: "NoSchedule"
    
    nodeSelector:
      monitoring: "true"
  
  # Disable other components (single binary mode)
  backend:
    replicas: 0
  read:
    replicas: 0
  write:
    replicas: 0
  
  # Gateway
  gateway:
    enabled: true
    replicas: 1
    
    resources:
      requests:
        memory: 128Mi
        cpu: 100m
      limits:
        memory: 256Mi
        cpu: 200m
    
    tolerations:
    - key: "monitoring"
      operator: "Equal"
      value: "true"
      effect: "NoSchedule"
    
    nodeSelector:
      monitoring: "true"

# Disable monitoring features
monitoring:
  selfMonitoring:
    enabled: false
    grafanaAgent:
      installOperator: false
  lokiCanary:
    enabled: false

# Disable test
test:
  enabled: false

# Disable tracing
tracing:
  jaegerAgentHost: ""