loki:
  # Use test schema for quick setup
  useTestSchema: true
  
  auth_enabled: false
  
  commonConfig:
    replication_factor: 1
  
  storage:
    type: filesystem
    bucketNames:
      chunks: chunks
      ruler: ruler
      admin: admin
    filesystem:
      chunks_directory: /var/loki/chunks
      rules_directory: /var/loki/rules
  
  # Limits and retention
  limits_config:
    retention_period: 30d
    ingestion_rate_mb: 10
    ingestion_burst_size_mb: 20
  
  # Compactor for retention
  compactor:
    working_directory: /var/loki/compactor
    compaction_interval: 10m
    retention_enabled: true
  
  # Single binary mode
  deploymentMode: SingleBinary
  
  singleBinary:
    replicas: 1
    
    persistence:
      enabled: true
      size: 80Gi
      storageClassName: "local-path"
    
    resources:
      requests:
        memory: 512Mi
        cpu: 250m
      limits:
        memory: 2Gi
        cpu: 1000m
    
    tolerations:
    - key: "monitoring"
      operator: "Equal"
      value: "true"
      effect: "NoSchedule"
    
    nodeSelector:
      monitoring: "true"
  
  backend:
    replicas: 0
  read:
    replicas: 0
  write:
    replicas: 0
  
  gateway:
    enabled: true
    replicas: 1
    
    tolerations:
    - key: "monitoring"
      operator: "Equal"
      value: "true"
      effect: "NoSchedule"
    
    nodeSelector:
      monitoring: "true"

monitoring:
  selfMonitoring:
    enabled: false
    grafanaAgent:
      installOperator: false
  lokiCanary:
    enabled: false

test:
  enabled: false